/*
 * jmenue.java - provides a Swing console for JavaBot
 *
 * Copyright (C) 2001 by Warren Milburn
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

package org.javabot.gui;

import java.awt.*;
import java.util.logging.Logger;

public class jmenue extends javax.swing.JFrame {

    final Logger log = Logger.getLogger(this.getClass().getName());

    private final JavaBotActivator jba;

    /** Creates new form jmenue */
    public jmenue() {
        log.info("jmenue() called");
        initComponents ();
        setJMenuBar(this.connectionMenuBar);
        pack ();
        jba = new JavaBotActivator(consoleOutput);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
            connectionMenuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
            connectMenuItem = new javax.swing.JMenuItem();
            disconnectMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu aboutMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem javaBotMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu configMenu = new javax.swing.JMenu();
            javaBotSettingsMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem userManagerMenuItem = new javax.swing.JMenuItem();
        javax.swing.JScrollPane consoleScrollPane = new javax.swing.JScrollPane();
            consoleOutput = new javax.swing.JTextArea();
        javax.swing.JTextField consoleInput = new javax.swing.JTextField();
        javax.swing.JToolBar mainToolBar = new javax.swing.JToolBar();
            conDisconButton = new javax.swing.JToggleButton();
            
            fileMenu.setText("File");
            connectMenuItem.setText("Connect");
            connectMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem1ActionPerformed(evt);
                }
            });
            
            fileMenu.add(connectMenuItem);
            disconnectMenuItem.setText("Disconnect");
            disconnectMenuItem.setEnabled(false);
            disconnectMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem2ActionPerformed(evt);
                }
            });
            
            fileMenu.add(disconnectMenuItem);
            exitMenuItem.setText("Exit");
            exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem3ActionPerformed(evt);
                }
            });
            
            fileMenu.add(exitMenuItem);
            connectionMenuBar.add(fileMenu);
          aboutMenu.setText("About");
            javaBotMenuItem.setText("JavaBot");
            javaBotMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    javaBotMenuItemActionPerformed(evt);
                }
            });
            
            aboutMenu.add(javaBotMenuItem);
            connectionMenuBar.add(aboutMenu);
          configMenu.setText("Config");
            javaBotSettingsMenuItem.setText("JavaBot");
            javaBotSettingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    javaBotSettingsMenuItemActionPerformed(evt);
                }
            });
            
            configMenu.add(javaBotSettingsMenuItem);
            userManagerMenuItem.setText("User Manager");
            userManagerMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    userManagerMenuItemActionPerformed(evt);
                }
            });
            
            configMenu.add(userManagerMenuItem);
            connectionMenuBar.add(configMenu);
          
          setTitle("JavaBot");
          setResizable(false);
          addWindowListener(new java.awt.event.WindowAdapter() {
              public void windowClosing(java.awt.event.WindowEvent evt) {
                  exitForm(evt);
              }
          });
          
          consoleScrollPane.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
          consoleScrollPane.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
          consoleOutput.setLineWrap(true);
          consoleOutput.setEditable(false);
          consoleOutput.setColumns(80);
          consoleOutput.setRows(20);
          consoleOutput.setFont(new java.awt.Font("Lucida Console", Font.PLAIN, 12));
          consoleScrollPane.setViewportView(consoleOutput);
          
          getContentPane().add(consoleScrollPane, java.awt.BorderLayout.CENTER);
          
          getContentPane().add(consoleInput, java.awt.BorderLayout.SOUTH);

            conDisconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("disconnected.gif")));
        conDisconButton.setToolTipText("Click to Connect");
          conDisconButton.setBorder(new javax.swing.border.EtchedBorder());
            conDisconButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("connected.gif")));
        conDisconButton.setName("");
          conDisconButton.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  conDisconButtonActionPerformed(evt);
              }
          });
          
          mainToolBar.add(conDisconButton);
          
          getContentPane().add(mainToolBar, java.awt.BorderLayout.NORTH);
        
    }//GEN-END:initComponents

    @SuppressWarnings("deprecation")
    private void userManagerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagerMenuItemActionPerformed
        // Add your handling code here:
        new UserUI().show();
    }//GEN-LAST:event_userManagerMenuItemActionPerformed

    @SuppressWarnings("deprecation")
    private void javaBotSettingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaBotSettingsMenuItemActionPerformed
        new ConfigUI().show();
    }//GEN-LAST:event_javaBotSettingsMenuItemActionPerformed

  private void conDisconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conDisconButtonActionPerformed
      if (jba.isConnected()) {
          jba.disconnect();
          conDisconButton.setToolTipText("Click to Connect");
          javaBotSettingsMenuItem.setEnabled(true);
          disconnectMenuItem.setEnabled(false);
          connectMenuItem.setEnabled(true);
      }
      else {
          jba.connect();
          conDisconButton.setToolTipText("Click to Disconnect");
          javaBotSettingsMenuItem.setEnabled(false);
          disconnectMenuItem.setEnabled(true);
          connectMenuItem.setEnabled(false);
      }
  }//GEN-LAST:event_conDisconButtonActionPerformed

  @SuppressWarnings("deprecation")
  private void javaBotMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaBotMenuItemActionPerformed
     new AboutDialog (new javax.swing.JFrame (), true).show ();
  }//GEN-LAST:event_javaBotMenuItemActionPerformed

  private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      if (jba.isConnected()) jba.disconnect();
      System.exit (0);
  }//GEN-LAST:event_jMenuItem3ActionPerformed
  
  private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

      // disconnect
      
      if (jba.isConnected()) {
              conDisconButton.doClick();
      }
  }//GEN-LAST:event_jMenuItem2ActionPerformed
  
  private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      
      // connect
      
      if (!jba.isConnected()) {
              conDisconButton.doClick();
      }
  }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        if (jba.isConnected()) jba.disconnect();
        //this.setVisible(false);
        System.exit (0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */

    public static void main (String[] args) {
        new jmenue().setVisible(true);
    }
    
    public void write(String toWrite) {
        consoleOutput.append(toWrite);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar connectionMenuBar;
    private javax.swing.JMenuItem connectMenuItem;
    private javax.swing.JMenuItem disconnectMenuItem;
    private javax.swing.JMenuItem javaBotSettingsMenuItem;
    private javax.swing.JTextArea consoleOutput;
    private javax.swing.JToggleButton conDisconButton;
    // End of variables declaration//GEN-END:variables

}
